# Generated by Django 5.2.10 on 2026-02-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("samples", "0003_remove_sample_biosample_accession_sample_biosample_and_more"),
        ("versions", "0008_alter_ingestversion_source_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accession", models.CharField(max_length=100)),
                ("read_count", models.BigIntegerField(blank=True, null=True)),
                (
                    "sequencer",
                    models.CharField(
                        blank=True,
                        help_text="Sequencing platform, e.g. Illumina NovaSeq 6000",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="versions.ingestversion",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "unique_together": {("accession", "ingest")},
            },
        ),
    ]
