# Generated by Django 5.2.10 on 2026-05-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
        ("versions", "0012_alter_ingestversion_upstream_version"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="run",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="run",
            name="library_source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="library_strategy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="previous_ingest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_for_runs",
                to="versions.ingestversion",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="accession",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="run",
            name="sequencer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
