# Generated by Django 5.2.10 on 2026-05-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_alter_run_unique_together_run_library_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="previous_ingest",
        ),
    ]
