# Generated by Django 5.2.10 on 2026-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0003_remove_run_previous_ingest"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="archive_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
