# Generated by Django 5.2.10 on 2026-02-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_remove_sample_biosample_accession_sample_biosample_and_more"),
        ("versions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Version",
            new_name="IngestVersion",
        ),
    ]
