# Generated by Django 5.2.10 on 2026-02-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0003_cartogenomicsrelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestversion",
            name="data_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="ingestversion",
            name="pipeline_version",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ingestversion",
            name="query",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ingestversion",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingests",
                to="versions.cartogenomicsrelease",
            ),
        ),
        migrations.AddField(
            model_name="ingestversion",
            name="source_system",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="ingestversion",
            name="upstream_last_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestversion",
            name="upstream_version",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
