# Generated by Django 5.2.10 on 2026-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0004_ingestversion_data_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ingestversion",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ingestversion",
            name="data_type",
            field=models.CharField(default="SAMPLE_METADATA", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingestversion",
            name="source_system",
            field=models.CharField(default="SAMPLE_METADATA", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="ingestversion",
            unique_together={("source_system", "data_type", "label")},
        ),
    ]
