# Generated by Django 5.2.10 on 2026-02-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0005_alter_ingestversion_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingestversion",
            name="source",
        ),
    ]
