# Generated by Django 5.2.10 on 2026-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0006_remove_ingestversion_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestversion",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("SAMPLE_METADATA", "Sample metadata"),
                    ("READS", "reads"),
                    ("GENOME", "genome"),
                    ("ABUNDANCE_RAW", "abundance raw"),
                    ("ABUNDANCE_PARQUET", "Abundance parquet"),
                    ("RO_CRATE", "RO-crate"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ingestversion",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("BIOSAMPLES", "BioSamples"),
                    ("ENA", "ENA"),
                    ("MGNIFY", "MGnify"),
                    ("BIOSTUDIES", "BioStudies"),
                    ("INTERNAL", "Internal"),
                ],
                max_length=32,
            ),
        ),
    ]
