# Generated by Django 5.2.10 on 2026-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0007_alter_ingestversion_data_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestversion",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("BIOSAMPLES", "BioSamples"),
                    ("ENA", "ENA"),
                    ("BIOSTUDIES", "BioStudies"),
                    ("INTERNAL", "Internal"),
                ],
                max_length=32,
            ),
        ),
    ]
