# Generated by Django 5.2.10 on 2026-03-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0008_alter_ingestversion_source_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingestversion",
            name="query",
        ),
    ]
