# Generated by Django 5.2.10 on 2026-03-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0009_remove_ingestversion_query"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingestversion",
            old_name="upstream_last_modified",
            new_name="last_modified_internal",
        ),
        migrations.RemoveField(
            model_name="ingestversion",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="ingestversion",
            name="upstream_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downstream_versions",
                to="versions.ingestversion",
            ),
        ),
    ]
