# Generated by Django 5.2.10 on 2026-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0011_ingestversion_retrieved_at_to_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestversion",
            name="upstream_version",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
