# Generated by Django 5.2.10 on 2026-05-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0012_alter_ingestversion_upstream_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingestversion",
            old_name="created_at",
            new_name="ingested_on",
        ),
        migrations.RemoveField(
            model_name="ingestversion",
            name="last_modified_internal",
        ),
    ]
