# Generated by Django 5.2.10 on 2026-07-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0013_rename_created_at_ingestversion_ingested_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestversion",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("SAMPLE_METADATA", "Sample metadata"),
                    ("READS", "reads"),
                    ("GENOME", "genome"),
                    ("ABUNDANCE_RAW", "abundance raw"),
                    ("ABUNDANCE_PARQUET", "Abundance parquet"),
                    ("RO_CRATE", "RO-crate"),
                    ("COUNTRY_BOUNDARIES", "Country boundaries"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ingestversion",
            name="source_system",
            field=models.CharField(
                choices=[
                    ("BIOSAMPLES", "BioSamples"),
                    ("ENA", "ENA"),
                    ("BIOSTUDIES", "BioStudies"),
                    ("INTERNAL", "Internal"),
                    ("NATURAL_EARTH", "Natural Earth"),
                ],
                max_length=32,
            ),
        ),
    ]
