# Generated by Django 5.2.10 on 2026-02-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("samples", "0003_remove_sample_biosample_accession_sample_biosample_and_more"),
        ("versions", "0008_alter_ingestversion_source_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accession", models.CharField(max_length=100)),
                ("completeness", models.FloatField(blank=True, null=True)),
                ("contamination", models.FloatField(blank=True, null=True)),
                ("genome_size", models.BigIntegerField(blank=True, null=True)),
                ("n50", models.BigIntegerField(blank=True, null=True)),
                ("taxonomy", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="genomes",
                        to="versions.ingestversion",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genomes",
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "unique_together": {("accession", "ingest")},
            },
        ),
    ]
