# Generated by Django 5.2.10 on 2026-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genome",
            name="sample",
        ),
        migrations.AddField(
            model_name="genome",
            name="completeness_software",
            field=models.CharField(
                choices=[
                    ("checkm", "CheckM"),
                    ("checkm2", "CheckM2"),
                    ("busco", "BUSCO"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
