# Generated by Django 5.2.10 on 2026-05-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomes", "0002_remove_genome_sample_genome_completeness_software"),
        ("versions", "0012_alter_ingestversion_upstream_version"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="genome",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="genome",
            name="previous_ingest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_for_genomes",
                to="versions.ingestversion",
            ),
        ),
        migrations.AlterField(
            model_name="genome",
            name="accession",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
