# Generated by Django 5.2.10 on 2026-05-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "genomes",
            "0003_alter_genome_unique_together_genome_previous_ingest_and_more",
        ),
        ("versions", "0012_alter_ingestversion_upstream_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genome",
            name="previous_ingest",
        ),
        migrations.CreateModel(
            name="GenomeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("completeness", models.FloatField(blank=True, null=True)),
                ("contamination", models.FloatField(blank=True, null=True)),
                ("completeness_software", models.CharField(default="", max_length=50)),
                ("genome_size", models.BigIntegerField(blank=True, null=True)),
                ("n50", models.BigIntegerField(blank=True, null=True)),
                ("taxonomy", models.TextField(blank=True, default="")),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="genomes.genome",
                    ),
                ),
                (
                    "ingest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="genome_versions",
                        to="versions.ingestversion",
                    ),
                ),
            ],
            options={
                "ordering": ["valid_from"],
            },
        ),
    ]
