# Generated by Django 5.2.10 on 2026-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genomes", "0004_remove_genome_previous_ingest_genomeversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="genome",
            name="archive_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genome",
            name="archive_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
