# Generated by Django 5.2.10 on 2026-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="location",
            new_name="locality",
        ),
        migrations.AddField(
            model_name="sample",
            name="geography_check_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASS", "Pass"),
                    ("WARN", "Warn"),
                    ("FAIL", "Fail"),
                    ("SKIP", "Skip"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="geography_status_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ocean_or_sea", "Ocean Or Sea"),
                    ("no_coordinates", "No Coordinates"),
                    ("no_reported_country_code", "No Reported Country Code"),
                    ("reverse_geocoder_no_result", "Reverse Geocoder No Result"),
                    (
                        "reported_cc_not_supported_by_reverse_geocoder",
                        "Reported Cc Not Supported By Reverse Geocoder",
                    ),
                    ("match", "Match"),
                    ("country_mismatch", "Country Mismatch"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="ontology",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="region",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
