# Generated by Django 5.2.10 on 2026-02-10 10:05

from django.db import migrations, models

import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_rename_location_sample_locality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="biosample_accession",
        ),
        migrations.AddField(
            model_name="sample",
            name="biosample",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[samples.models.validate_biosample],
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="ena_sample",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[samples.models.validate_ena_sample],
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="source_dataset",
            field=models.CharField(
                choices=[("MFD", "Mfd"), ("GTDB", "Gtdb"), ("ENA", "Ena")],
                default="",
                max_length=50,
            ),
        ),
    ]
