# Generated by Django 5.2.10 on 2026-03-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_remove_sample_biosample_accession_sample_biosample_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="version",
            new_name="ingest",
        ),
    ]
