# Generated by Django 5.2.10 on 2026-03-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0004_rename_version_sample_ingest"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="completeness_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="contamination_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="qc_software",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
