# Generated by Django 5.2.10 on 2026-03-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "samples",
            "0005_sample_completeness_score_sample_contamination_score_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sample",
            old_name="qc_software",
            new_name="completeness_software",
        ),
    ]
