# Generated by Django 5.2.10 on 2026-03-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0006_rename_qc_software_sample_completeness_software"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="completeness_score",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="completeness_software",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="contamination_score",
        ),
    ]
