# Generated by Django 5.2.10 on 2026-05-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0007_remove_sample_completeness_score_and_more"),
        ("versions", "0012_alter_ingestversion_upstream_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="previous_ingest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_for_samples",
                to="versions.ingestversion",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="ingest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="samples",
                to="versions.ingestversion",
            ),
        ),
    ]
