# Generated by Django 5.2.10 on 2026-05-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0008_sample_previous_ingest_alter_sample_ingest"),
        ("versions", "0012_alter_ingestversion_upstream_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="previous_ingest",
        ),
        migrations.CreateModel(
            name="SampleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("biosample", models.CharField(blank=True, max_length=50, null=True)),
                ("ena_sample", models.CharField(blank=True, max_length=50, null=True)),
                ("source_dataset", models.CharField(default="", max_length=50)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=1000, null=True)),
                ("locality", models.CharField(blank=True, max_length=1000, null=True)),
                ("ontology", models.CharField(blank=True, null=True)),
                (
                    "geography_check_status",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "geography_status_reason",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("raw_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ingest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sample_versions",
                        to="versions.ingestversion",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "ordering": ["valid_from"],
            },
        ),
    ]
