# Generated by Django 5.2.10 on 2026-05-27 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0009_remove_sample_previous_ingest_sampleversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="archive_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="archive_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sampleversion",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="samples.sample",
            ),
        ),
    ]
