# Generated by Django 5.2.10 on 2026-07-16 08:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0010_sample_archive_created_sample_archive_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="coord_precision_deg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="coordinates_reversed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="inferred_country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="sampleversion",
            name="coord_precision_deg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sampleversion",
            name="coordinates_reversed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sampleversion",
            name="inferred_country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="sampleversion",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="geography_status_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ocean_or_sea", "Ocean Or Sea"),
                    ("no_coordinates", "No Coordinates"),
                    ("null_island", "Null Island"),
                    ("identical_lat_long", "Identical Lat Long"),
                    (
                        "coordinates_suspiciously_round",
                        "Coordinates Suspiciously Round",
                    ),
                    ("implausibly_precise", "Implausibly Precise"),
                    ("centroid_or_capital", "Centroid Or Capital"),
                    ("known_institution", "Known Institution"),
                    ("match_territory", "Match Territory"),
                    ("small_island_not_in_reference", "Small Island Not In Reference"),
                    ("no_reported_country_code", "No Reported Country Code"),
                    (
                        "disputed_or_unrecognised_territory",
                        "Disputed Or Unrecognised Territory",
                    ),
                    ("match", "Match"),
                    ("match_near_border", "Match Near Border"),
                    ("country_mismatch", "Country Mismatch"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
    ]
